from tkinter import *
from tkinter import messagebox
import qrcode as qr

pwin=Tk()
pwin.state('zoomed')
pwin.configure(bg='powder blue')
pwin.resizable(width=False,height=False)


header_frm=Frame(pwin)
header_frm.configure(bg='pink')
header_frm.place(x=0,y=0,relwidth=1,relheight=0.25)


title_lbl=Label(header_frm,text="QR Generating System",font=('',25,'bold'),bg='pink')
title_lbl.pack()





def start_page():
    def admin_page():
        messagebox.showinfo("welcome admin","redirecting to admin Login")
        frm.destroy() 
        main_body()
        
        
        
                
    frm=Frame(pwin)
    frm.configure(bg='powder blue')
    frm.place(x=0,rely=0.2,relwidth=1,relheight=0.75)
    admin_btn=Button(frm,text="  Admin Login   ",font=('',20,'bold'),bd=6,command=admin_page)
    admin_btn.place(relx=0.4,rely=.35)


def main_body():
    def clearit():
        user_entry.delete(0,"end")
        pwd_entry.delete(0,"end")
        user_entry.focus()
    def login():
        uid=user_entry.get()
        pwd=pwd_entry.get()
        if(len(uid)==0 or len(pwd)==0):
            messagebox.showwarning("validation","Username/ password  can't be left empty")
        else:
            if uid=="abc" and pwd=="xyz":
                
                messagebox.showinfo("Welcome","Admin :"+ uid)
                frm.destroy()
                login_body()
            else:
                messagebox.showerror("Error","Wrong id or password")
                

            
    frm=Frame(pwin)
    admin_welcome_lbl=Label(frm,text="-----------Admin Area---------",font=('',20,'bold'),bg='powder blue')
    admin_welcome_lbl.place(relx=0.1,rely=0.05)            
    
    frm.configure(bg='powder blue')
    frm.place(x=0,rely=0.2,relwidth=1,relheight=0.75)
    user_lbl=Label(frm,text="Admin Id:",font=('',20,'bold'),bg='powder blue')
    user_lbl.place(relx=0.3,rely=0.15)
    user_entry=Entry(frm,font=('',20,'bold'),bd=6)
    user_entry.place(relx=0.5,rely=0.15)
    pwd_lbl=Label(frm,text="Password",font=('',20,'bold'),bg='powder blue')
    pwd_lbl.place(relx=0.3,rely=0.30)
    pwd_entry=Entry(frm,font=('',20,'bold'),bd=6,show="#")
    pwd_entry.place(relx=0.5,rely=0.30)
    login_btn=Button(frm,text="Login",font=('',20,'bold'),bd=6,command=login)
    login_btn.place(relx=0.40,rely=.45)
    login_clear=Button(frm,text="Clear",font=('',20,'bold'),bd=6,command=clearit)
    login_clear.place(relx=0.50,rely=.45)
    back_home=Button(frm,text="Home screen",font=('',20,'bold'),bd=6,command=start_page)
    back_home.place(relx=0.60,rely=.75)

    
def login_body():
    def create_QR():
        qraddr=url_entry.get()
        imgaddr=image_entry.get()
        qrval=qr.make(qraddr)
        qrval.save(imgaddr)
        messagebox.showinfo("your qr code is generated by name check your code folder :",imgaddr)

        
        

        

    def log_out():
        messagebox.showinfo("Thank you for using this application","Logout successfully")
        frm.destroy()
        main_body()

        
    
    frm=Frame(pwin)
    frm.configure(bg='powder blue')
    frm.place(x=0,rely=0.25,relwidth=1,relheight=0.75)
    welcome_lbl=Label(frm,text="Welcome admin",font=('',20,'bold'),bg='powder blue')
    welcome_lbl.place(relx=0,rely=0)
    logout_btn=Button(frm,text="logout",font=('',20,'bold'),bd=6,command=log_out)
    logout_btn.place(relx=0.91,rely=0)
    url_lbl=Label(frm,text="Enter URL or String",font=('',20,'bold'),bg='powder blue')
    url_lbl.place(relx=0.2,rely=0.15)
    url_entry=Entry(frm,font=('',20,'bold'),bd=6)
    url_entry.place(relx=0.5,rely=0.15)
    
    image_lbl=Label(frm,text="Enter Image name or url",font=('',20,'bold'),bg='powder blue')
    image_lbl.place(relx=0.2,rely=0.30)
    image_entry=Entry(frm,font=('',20,'bold'),bd=6)
    image_entry.place(relx=0.5,rely=0.30)
    create_QR=Button(frm,text="Create QR code",font=('',20,'bold'),bd=6,width=15,command=create_QR)
    create_QR.place(relx=0.4,rely=0.45)
    
    
start_page()
pwin.mainloop()